on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - uses: actions/checkout@v4

      - run: go test -race -count=3 -tags ego_mpc_mock ./...

  example:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/edgelesssys/ego-dev

    steps:
      - uses: actions/checkout@v4

      - run: ./test.sh
        working-directory: example
